#staff http://localhost:3000/api/users/staff/

### Register

POST http://localhost:3000/api/users/staff/register/
Content-Type: application/json

{
    "email": "staff@gmail.com",
    "password":"123456",
    "name": "SoloStaff"
}


### Login

POST  http://localhost:3000/api/users/staff/login
Content-Type: application/json

{
    "email": "staff@gmail.com",
    "password":"123456"
}


### get Logged in User Info

get  http://localhost:3000/api/users/staff/info
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGFmZlVzZXIiOnsiaWQiOiI2MmVmYTlmNmU5MzNkZDRkMTE2NTkyMTUifSwiaWF0IjoxNjU5ODczNzgzLCJleHAiOjE2NjAyMzM3ODN9.VENNWzw7zcvmWU7_iz6S6RdMFHksy-xMOp5PGLa9D5k


### Get All Orders

get  http://localhost:3000/api/users/staff/orders/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGFmZlVzZXIiOnsiaWQiOiI2MmVmYTlmNmU5MzNkZDRkMTE2NTkyMTUifSwiaWF0IjoxNjU5ODczNzgzLCJleHAiOjE2NjAyMzM3ODN9.VENNWzw7zcvmWU7_iz6S6RdMFHksy-xMOp5PGLa9D5k

### Get a Menu

get  http://localhost:3000/api/menus/62ef2884f949bb48e3772ff4
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVXNlciI6eyJpZCI6IjYyZWYyNDNjYWFkZjgyNmE2MTg5ZmUxZiIsImVtYWlsIjoidXNlckBnbWFpbC5jb20ifSwiaWF0IjoxNjU5ODcxODI2LCJleHAiOjE2NjAyMzE4MjZ9.hWpMuVnUpPRJKi7BwIg8xQ04AtsIYD18pYg0tpT91e4

### Get all order

get  http://localhost:3000/api/users/staff/orders/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGFmZlVzZXIiOnsiaWQiOiI2MmVmYTlmNmU5MzNkZDRkMTE2NTkyMTUifSwiaWF0IjoxNjU5ODczNzgzLCJleHAiOjE2NjAyMzM3ODN9.VENNWzw7zcvmWU7_iz6S6RdMFHksy-xMOp5PGLa9D5k

### Get an order

get http://localhost:3000/api/users/staff/orders/62efa1e68876d5aedb0094b7
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGFmZlVzZXIiOnsiaWQiOiI2MmVmYTlmNmU5MzNkZDRkMTE2NTkyMTUifSwiaWF0IjoxNjU5ODczNzgzLCJleHAiOjE2NjAyMzM3ODN9.VENNWzw7zcvmWU7_iz6S6RdMFHksy-xMOp5PGLa9D5k


### Take an order

get  http://localhost:3000/api/users/staff/take-orders/62efa4d44ce9920bd25e4f0f
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGFmZlVzZXIiOnsiaWQiOiI2MmVmYTlmNmU5MzNkZDRkMTE2NTkyMTUifSwiaWF0IjoxNjU5ODczNzgzLCJleHAiOjE2NjAyMzM3ODN9.VENNWzw7zcvmWU7_iz6S6RdMFHksy-xMOp5PGLa9D5k

### My-Orders

GET  http://localhost:3000/api/users/staff/my-orders/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGFmZlVzZXIiOnsiaWQiOiI2MmVmYTlmNmU5MzNkZDRkMTE2NTkyMTUifSwiaWF0IjoxNjU5ODczNzgzLCJleHAiOjE2NjAyMzM3ODN9.VENNWzw7zcvmWU7_iz6S6RdMFHksy-xMOp5PGLa9D5k
